<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net11.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
    <StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
    <_ComputeCallerFileNamePrefixAssemblyPath>$(MSBuildThisFileDirectory)..\..\BlazorJSComponents.Tasks\bin\$(Configuration)\netstandard2.0\BlazorJSComponents.Tasks.dll</_ComputeCallerFileNamePrefixAssemblyPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.12" Condition="'$(TargetFramework)' == 'net10.0'" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="11.0.0-rc.1.26425.128" Condition="'$(TargetFramework)' == 'net11.0'" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BlazorJSComponents\BlazorJSComponents.csproj" />
    <ProjectReference Include="..\..\BlazorJSComponents.Tasks\BlazorJSComponents.Tasks.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
      <PrivateAssets>all</PrivateAssets>
    </ProjectReference>
  </ItemGroup>

  <Import Project="..\..\BlazorJSComponents\build\BlazorJSComponents.targets" />

</Project>
