<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net11.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <_ComputeCallerFileNamePrefixAssemblyPath>$(MSBuildThisFileDirectory)..\..\BlazorJSComponents.Tasks\bin\$(Configuration)\netstandard2.0\BlazorJSComponents.Tasks.dll</_ComputeCallerFileNamePrefixAssemblyPath>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BlazorJSComponents\BlazorJSComponents.csproj" />
    <ProjectReference Include="..\..\BlazorJSComponents.Tasks\BlazorJSComponents.Tasks.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
      <PrivateAssets>all</PrivateAssets>
    </ProjectReference>
  </ItemGroup>

  <Import Project="..\..\BlazorJSComponents\build\BlazorJSComponents.targets" />

</Project>
